### ISSUE TITLE
Can you tell me what algorithm you used for doomsday fuel?

### ISSUE THREAD

**Issue by zhubohao911** [Trismeg/FooBar#1]
I am very confused about your code. 
I am struggling with this problem for a long time.
What fuse method do? I wrote a solution using absorbing Markov chain but fail test 8.

Thanks

**Comment by Trismeg** [comment]
It’s been some time since I worked on this.  The fuse method is used to determine the markov weights.  The error you are getting might be because you are not reducing the weights if they all have a greatest common denominator.

**Comment by zhubohao911** [comment]
@Trismeg thanks man
